### ISSUE TITLE
Doesn't work with addon-sdk-1.17

### ISSUE THREAD

**Issue by lebedev** [ZER0/penny-arcade-comics#1]
Hi! I was going to write my add-on basing on yours, but sadly it doesn't work with addon-sdk-1.17 and Firefox Mobile Beta 36 and Firefox Mobile 34. Is there any chance you'll update it?

**Comment by lebedev** [comment]
Nevermind. I've found a way to make your add-on work.

**Comment by ZER0** [comment]
Hi! Sorry @zeird, this comment slip under the radar, I notice it only today; I definitely need a better filter in my email. Happy that you solve your issue; this code it's really old and I'm not sure it's still working on Fennec – SDK has been discontinued on supporting Firefox Mobile. Let me know if you need further information about that; you can also reach me – and the jetpack team on #jetpack channel in irc.mozilla.org

**Comment by lebedev** [comment]
> SDK has been discontinued on supporting Firefox Mobile.

Is it so?

> Let me know if you need further information about that

Thanks, but I've figured it out.
My issue was that `page-mod` doesn't work with `Firefox Mobile _Beta_` because of [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1123295).
And `contentStyleFile` of `page-mod` doesn't work with `Firefox Mobile` because of [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1107240).
And I had to `--force-mobile` when `cfx`'ed my add-on.
Now it works just fine.

**Comment by ZER0** [comment]
> > SDK has been discontinued on supporting Firefox Mobile.
> 
> Is it so?

When I made this example, Fennec was a priority for SDK. Unfortunately the priorities now are different due some internal changes in jetpack team, and the requested infrastructure to having proper integration test on Fennec was never granted. Therefore, it's too easy break SDK on Fennec 'cause we don't have automated tests that run every time we commit a patch, and the support for Fennec was decided to kept as experimental. I'd love having proper support for it, and I'm hoping this will change in the future, but so far that's the situation. 

> Thanks, but I've figured it out.

Glad to hear!
